"""empty message

Revision ID: 5789576d1e12
Revises: 260afb6b23f0
Create Date: 2022-03-20 03:07:51.221727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5789576d1e12'
down_revision = '260afb6b23f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('descr', sa.String(length=800), nullable=True))
    op.drop_column('properties', 'Descr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('Descr', sa.VARCHAR(length=800), autoincrement=False, nullable=True))
    op.drop_column('properties', 'descr')
    # ### end Alembic commands ###
